[package]
name = "classicube-chatsounds-plugin"
version = "3.5.9"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
chatsounds = { git = "https://github.com/SpiralP/rust-chatsounds.git" }
classicube-helpers = { git = "https://github.com/SpiralP/rust-classicube-helpers.git", features = ["futures"] }
classicube-sys = { git = "https://github.com/SpiralP/rust-classicube-sys.git" }
color-backtrace = { git = "https://github.com/SpiralP/color-backtrace-msgbox.git" }
crossbeam-channel = "0.4.4"
env_logger = "0.7.1"
futures = "0.3.6"
lazy_static = "1.4.0"
log = "0.4.11"
parking_lot = "0.11.0"
rand = "0.7.3"
rand_chacha = "0.2.2"
tokio = { version = "0.2.22", features = ["full"] }



[package.metadata.release]
disable-publish = true
pre-release-commit-message = "Release {{version}}"
post-release-commit-message = "Begin {{next_version}}"
tag-message = "Release version {{version}}"


# fix them using old bindgen versions
[patch.crates-io]
coreaudio-sys = { git = "https://github.com/SpiralP/coreaudio-sys.git" }
